var annotated_dup =
[
    [ "builder", null, [
      [ "ComponentDefinition", "structbuilder_1_1ComponentDefinition.html", "structbuilder_1_1ComponentDefinition" ],
      [ "ComponentInstantiation", "structbuilder_1_1ComponentInstantiation.html", "structbuilder_1_1ComponentInstantiation" ],
      [ "Parameter", "structbuilder_1_1Parameter.html", "structbuilder_1_1Parameter" ],
      [ "ParameterArray", "structbuilder_1_1ParameterArray.html", null ],
      [ "ParameterMap", "structbuilder_1_1ParameterMap.html", "structbuilder_1_1ParameterMap" ],
      [ "ParameterMapItem", "structbuilder_1_1ParameterMapItem.html", "structbuilder_1_1ParameterMapItem" ]
    ] ],
    [ "sinucaTracer", null, [
      [ "DataINS", "structsinucaTracer_1_1DataINS.html", null ],
      [ "DataMEM", "structsinucaTracer_1_1DataMEM.html", "structsinucaTracer_1_1DataMEM" ],
      [ "DynamicTraceFile", "classsinucaTracer_1_1DynamicTraceFile.html", "classsinucaTracer_1_1DynamicTraceFile" ],
      [ "InstructionInfo", "structsinucaTracer_1_1InstructionInfo.html", null ],
      [ "MemoryTraceFile", "classsinucaTracer_1_1MemoryTraceFile.html", "classsinucaTracer_1_1MemoryTraceFile" ],
      [ "SinucaTraceReader", "classsinucaTracer_1_1SinucaTraceReader.html", "classsinucaTracer_1_1SinucaTraceReader" ],
      [ "StaticTraceFile", "classsinucaTracer_1_1StaticTraceFile.html", "classsinucaTracer_1_1StaticTraceFile" ],
      [ "ThrInfo", "structsinucaTracer_1_1ThrInfo.html", "structsinucaTracer_1_1ThrInfo" ],
      [ "TraceFile", "structsinucaTracer_1_1TraceFile.html", null ],
      [ "TraceFileReader", "classsinucaTracer_1_1TraceFileReader.html", "classsinucaTracer_1_1TraceFileReader" ],
      [ "TraceFileWriter", "classsinucaTracer_1_1TraceFileWriter.html", "classsinucaTracer_1_1TraceFileWriter" ]
    ] ],
    [ "yaml", null, [
      [ "YamlMappingEntry", "structyaml_1_1YamlMappingEntry.html", "structyaml_1_1YamlMappingEntry" ],
      [ "YamlValue", "structyaml_1_1YamlValue.html", "structyaml_1_1YamlValue" ]
    ] ],
    [ "BimodalPredictor", "classBimodalPredictor.html", "classBimodalPredictor" ],
    [ "BranchTargetBuffer", "classBranchTargetBuffer.html", "classBranchTargetBuffer" ],
    [ "BTBEntry", "structBTBEntry.html", "structBTBEntry" ],
    [ "BTBPacket", "structBTBPacket.html", "structBTBPacket" ],
    [ "CircularBuffer", "classCircularBuffer.html", "classCircularBuffer" ],
    [ "Component", "classComponent.html", "classComponent" ],
    [ "ConfigArray", "structConfigArray.html", null ],
    [ "ConfigValue", "structConfigValue.html", null ],
    [ "Connection", "structConnection.html", "structConnection" ],
    [ "CustomExample", "classCustomExample.html", "classCustomExample" ],
    [ "DelayQueue", "classDelayQueue.html", "classDelayQueue" ],
    [ "DynamicInstructionInfo", "structDynamicInstructionInfo.html", null ],
    [ "Engine", "classEngine.html", "classEngine" ],
    [ "EngineBuilder", "classEngineBuilder.html", "classEngineBuilder" ],
    [ "EngineDebugComponent", "classEngineDebugComponent.html", "classEngineDebugComponent" ],
    [ "FetchBufferEntry", "structFetchBufferEntry.html", null ],
    [ "Fetcher", "classFetcher.html", "classFetcher" ],
    [ "FetchPacket", "unionFetchPacket.html", "unionFetchPacket" ],
    [ "HardwiredPredictor", "classHardwiredPredictor.html", "classHardwiredPredictor" ],
    [ "InstructionPacket", "structInstructionPacket.html", null ],
    [ "InstructionQueue", "classInstructionQueue.html", null ],
    [ "Linkable", "classLinkable.html", "classLinkable" ],
    [ "MemoryQueue", "classMemoryQueue.html", null ],
    [ "PredictorPacket", "structPredictorPacket.html", "structPredictorPacket" ],
    [ "PredictorQueue", "classPredictorQueue.html", null ],
    [ "Queue", "classQueue.html", "classQueue" ],
    [ "QueueTester", "classQueueTester.html", "classQueueTester" ],
    [ "Ras", "classRas.html", "classRas" ],
    [ "SimpleCore", "classSimpleCore.html", "classSimpleCore" ],
    [ "SimpleExecutionUnit", "classSimpleExecutionUnit.html", "classSimpleExecutionUnit" ],
    [ "SimpleInstructionMemory", "classSimpleInstructionMemory.html", "classSimpleInstructionMemory" ],
    [ "SimpleMemory", "classSimpleMemory.html", "classSimpleMemory" ],
    [ "StaticInstructionInfo", "structStaticInstructionInfo.html", null ],
    [ "TraceReader", "classTraceReader.html", "classTraceReader" ]
];