var annotated_dup =
[
    [ "map", null, [
      [ "Node", "structmap_1_1Node.html", null ]
    ] ],
    [ "ReplacementPolicies", null, [
      [ "LRU", "classReplacementPolicies_1_1LRU.html", null ],
      [ "Random", "classReplacementPolicies_1_1Random.html", null ],
      [ "RoundRobin", "classReplacementPolicies_1_1RoundRobin.html", null ]
    ] ],
    [ "yaml", null, [
      [ "YamlLocation", "structyaml_1_1YamlLocation.html", null ],
      [ "YamlArray", "structyaml_1_1YamlArray.html", null ],
      [ "YamlValue", "structyaml_1_1YamlValue.html", "structyaml_1_1YamlValue" ],
      [ "Parser", "classyaml_1_1Parser.html", "classyaml_1_1Parser" ]
    ] ],
    [ "Arena", "classArena.html", null ],
    [ "BimodalCounter", "classBimodalCounter.html", "classBimodalCounter" ],
    [ "BoomFetch", "classBoomFetch.html", "classBoomFetch" ],
    [ "BoomFetchBufferEntry", "structBoomFetchBufferEntry.html", "structBoomFetchBufferEntry" ],
    [ "BranchTargetBuffer", "classBranchTargetBuffer.html", "classBranchTargetBuffer" ],
    [ "BTBEntry", "structBTBEntry.html", "structBTBEntry" ],
    [ "BTBPacket", "structBTBPacket.html", "structBTBPacket" ],
    [ "CacheLine", "structCacheLine.html", null ],
    [ "CacheMemory", "classCacheMemory.html", "classCacheMemory" ],
    [ "CircularBuffer", "classCircularBuffer.html", "classCircularBuffer" ],
    [ "Component", "classComponent.html", "classComponent" ],
    [ "Config", "classConfig.html", "classConfig" ],
    [ "Connection", "structConnection.html", "structConnection" ],
    [ "CustomExample", "classCustomExample.html", "classCustomExample" ],
    [ "Definition", "structDefinition.html", null ],
    [ "DelayQueue", "classDelayQueue.html", "classDelayQueue" ],
    [ "DynamicInstructionInfo", "structDynamicInstructionInfo.html", null ],
    [ "DynamicTraceReader", "classDynamicTraceReader.html", null ],
    [ "DynamicTraceRecord", "structDynamicTraceRecord.html", "structDynamicTraceRecord" ],
    [ "DynamicTraceWriter", "classDynamicTraceWriter.html", "classDynamicTraceWriter" ],
    [ "Engine", "classEngine.html", "classEngine" ],
    [ "EngineDebugComponent", "classEngineDebugComponent.html", "classEngineDebugComponent" ],
    [ "FetchBufferEntry", "structFetchBufferEntry.html", null ],
    [ "Fetcher", "classFetcher.html", "classFetcher" ],
    [ "FetchPacket", "unionFetchPacket.html", "unionFetchPacket" ],
    [ "FileHeader", "structFileHeader.html", "structFileHeader" ],
    [ "GsharePredictor", "classGsharePredictor.html", "classGsharePredictor" ],
    [ "HardwiredPredictor", "classHardwiredPredictor.html", "classHardwiredPredictor" ],
    [ "InstanceWithDefinition", "structInstanceWithDefinition.html", null ],
    [ "Instruction", "structInstruction.html", null ],
    [ "InstructionPacket", "structInstructionPacket.html", null ],
    [ "InstructionQueue", "classInstructionQueue.html", null ],
    [ "IntrinsicInfo", "structIntrinsicInfo.html", null ],
    [ "iTLB", "classiTLB.html", "classiTLB" ],
    [ "iTLBDebugComponent", "classiTLBDebugComponent.html", "classiTLBDebugComponent" ],
    [ "Linkable", "classLinkable.html", "classLinkable" ],
    [ "Map", "classMap.html", null ],
    [ "MemoryQueue", "classMemoryQueue.html", null ],
    [ "MemoryTraceReader", "classMemoryTraceReader.html", null ],
    [ "MemoryTraceRecord", "structMemoryTraceRecord.html", "structMemoryTraceRecord" ],
    [ "MemoryTraceWriter", "classMemoryTraceWriter.html", "classMemoryTraceWriter" ],
    [ "PredictorPacket", "structPredictorPacket.html", "structPredictorPacket" ],
    [ "PredictorQueue", "classPredictorQueue.html", null ],
    [ "Queue", "classQueue.html", "classQueue" ],
    [ "QueueTester", "classQueueTester.html", "classQueueTester" ],
    [ "Ras", "classRas.html", "classRas" ],
    [ "ReplacementPolicy", "classReplacementPolicy.html", null ],
    [ "SimpleCore", "classSimpleCore.html", "classSimpleCore" ],
    [ "SimpleExecutionUnit", "classSimpleExecutionUnit.html", "classSimpleExecutionUnit" ],
    [ "SimpleInstructionMemory", "classSimpleInstructionMemory.html", "classSimpleInstructionMemory" ],
    [ "SimpleMemory", "classSimpleMemory.html", "classSimpleMemory" ],
    [ "SinucaTraceReader", "classSinucaTraceReader.html", "classSinucaTraceReader" ],
    [ "StaticInstructionInfo", "structStaticInstructionInfo.html", null ],
    [ "StaticTraceReader", "classStaticTraceReader.html", "classStaticTraceReader" ],
    [ "StaticTraceRecord", "structStaticTraceRecord.html", "structStaticTraceRecord" ],
    [ "StaticTraceWriter", "classStaticTraceWriter.html", "classStaticTraceWriter" ],
    [ "StringMap", "classStringMap.html", null ],
    [ "ThreadData", "structThreadData.html", "structThreadData" ],
    [ "TLBRequest", "structTLBRequest.html", null ],
    [ "TraceDumperComponent", "classTraceDumperComponent.html", "classTraceDumperComponent" ],
    [ "TraceReader", "classTraceReader.html", "classTraceReader" ]
];