SiNUCA3: DelayQueue< Type > Class Template Reference
DelayQueue< Type > Class Template Reference
Classes
struct Input
Public Member Functions
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
Public Member Functions inherited from Component< Type >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, Type *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, Type *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
bool IsEmpty ()
bool IsFull ()
bool UseDelayBuffer ()
void SetDelayBufferSize ()
int Enqueue (Input *elem)
No insertion if full. If empty, the queueFirst is set with new elemToInsert. Otherwise, it is inserted in delay buffer.
int Dequeue (Input *elem)
No removal if empty or not time to remove queueFirst. Else, elemToRemove receives queueFirst and if occupation is greater than one, queueFirst receives the oldest input from delay buffer.
Private Attributes
Input queueFirst
CircularBuffer delayBuffer
Component< Type > * sendTo
unsigned long cyclesClock
unsigned long occupation
unsigned long delayBufferSize
unsigned long throughput
unsigned long delay
int sendToId
Additional Inherited Members
Protected Member Functions inherited from Component< Type >
int SendResponseToConnection (int connectionID, Type *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, Type *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
template<typename Type>
class DelayQueue< Type >
Definition at line 50 of file delay_queue.hpp.
Constructor & Destructor Documentation
DelayQueue()
template<typename Type > DelayQueue< Type >::DelayQueue ()
Definition at line 97 of file delay_queue.hpp.
~DelayQueue()
template<typename Type > DelayQueue< Type >::~DelayQueue () virtual
Definition at line 105 of file delay_queue.hpp.
Member Function Documentation
Clock()
template<typename Type > void DelayQueue< Type >::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 199 of file delay_queue.hpp.
References Component< MessageType >::SendRequest().
Dequeue()
template<typename Type > int DelayQueue< Type >::Dequeue (Input * elem) private
No removal if empty or not time to remove queueFirst. Else, elemToRemove receives queueFirst and if occupation is greater than one, queueFirst receives the oldest input from delay buffer.
Definition at line 125 of file delay_queue.hpp.
References CircularBuffer::Dequeue(), and DelayQueue< Type >::Input::removeAt.
Enqueue()
template<typename Type > int DelayQueue< Type >::Enqueue (Input * elem) private
No insertion if full. If empty, the queueFirst is set with new elemToInsert. Otherwise, it is inserted in delay buffer.
Definition at line 110 of file delay_queue.hpp.
References CircularBuffer::Enqueue().
FinishSetup()
template<typename Type > int DelayQueue< Type >::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 180 of file delay_queue.hpp.
References CircularBuffer::Allocate(), Component< MessageType >::Connect(), and SINUCA3_ERROR_PRINTF.
IsEmpty()
template<typename Type > bool DelayQueue< Type >::IsEmpty () inline private
Definition at line 68 of file delay_queue.hpp.
IsFull()
template<typename Type > bool DelayQueue< Type >::IsFull () inline private
Definition at line 69 of file delay_queue.hpp.
PrintStatistics()
template<typename Type > virtual void DelayQueue< Type >::PrintStatistics () inline virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 90 of file delay_queue.hpp.
SetConfigParameter()
template<typename Type > int DelayQueue< Type >::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 141 of file delay_queue.hpp.
SetDelayBufferSize()
template<typename Type > void DelayQueue< Type >::SetDelayBufferSize () inline private
Definition at line 71 of file delay_queue.hpp.
UseDelayBuffer()
template<typename Type > bool DelayQueue< Type >::UseDelayBuffer () inline private
Definition at line 70 of file delay_queue.hpp.
Member Data Documentation
cyclesClock
template<typename Type > unsigned long DelayQueue< Type >::cyclesClock private
A cycles clock>
Definition at line 61 of file delay_queue.hpp.
delay
template<typename Type > unsigned long DelayQueue< Type >::delay private
Number of cycles of delay>
Definition at line 65 of file delay_queue.hpp.
delayBuffer
template<typename Type > CircularBuffer DelayQueue< Type >::delayBuffer private
Used if delay >= 1
Definition at line 59 of file delay_queue.hpp.
delayBufferSize
template<typename Type > unsigned long DelayQueue< Type >::delayBufferSize private
Definition at line 63 of file delay_queue.hpp.
occupation
template<typename Type > unsigned long DelayQueue< Type >::occupation private
Definition at line 62 of file delay_queue.hpp.
queueFirst
template<typename Type > Input DelayQueue< Type >::queueFirst private
Oldest input in the delay buffer>
Definition at line 58 of file delay_queue.hpp.
sendTo
template<typename Type > Component<Type>* DelayQueue< Type >::sendTo private
Definition at line 60 of file delay_queue.hpp.
sendToId
template<typename Type > int DelayQueue< Type >::sendToId private
Definition at line 66 of file delay_queue.hpp.
throughput
template<typename Type > unsigned long DelayQueue< Type >::throughput private
Definition at line 64 of file delay_queue.hpp.
The documentation for this class was generated from the following file:
src/std_components/misc/delay_queue.hpp