SiNUCA3: EngineDebugComponent Class Reference
EngineDebugComponent Class Reference
A component that serves to debug the engine itself.
#include <engine_debug_component.hpp>
Public Member Functions
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< InstructionPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, InstructionPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, InstructionPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
void PrintConfigValue (const char *parameter, ConfigValue value, unsigned char indent=0)
If true, fails at the FinishSetup method to test the engine handling of failures.
Private Attributes
EngineDebugComponent * other
Component< FetchPacket > * fetch
Another component to test sending messages.
int otherConnectionID
Another component to test fetching instructions.
int fetchConnectionID
Connection ID for other.
bool send
Connection ID for fetch.
bool shallFailOnFinish
Tells wether we already sent a message to other.
Additional Inherited Members
Protected Member Functions inherited from Component< InstructionPacket >
int SendResponseToConnection (int connectionID, InstructionPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, InstructionPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
A component that serves to debug the engine itself.
The component will log with SINUCA3_DEBUG_PRINTF it's parameters along with their values. If passed the parameter "failNow" with any value, the method SetConfigParameter will return with failure. If passed the parameter "failOnFinish", the method FinishSetup will return with failure.
Definition at line 38 of file engine_debug_component.hpp.
Constructor & Destructor Documentation
EngineDebugComponent()
EngineDebugComponent::EngineDebugComponent () inline
Definition at line 62 of file engine_debug_component.hpp.
~EngineDebugComponent()
EngineDebugComponent::~EngineDebugComponent () virtual
Definition at line 172 of file engine_debug_component.cpp.
Member Function Documentation
Clock()
void EngineDebugComponent::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 117 of file engine_debug_component.cpp.
References fetch, fetchConnectionID, Linkable::GetNumberOfConnections(), otherConnectionID, Component< InstructionPacket >::ReceiveRequestFromConnection(), Component< MessageType >::ReceiveResponse(), FetchPacket::response, send, Component< MessageType >::SendRequest(), Component< InstructionPacket >::SendResponseToConnection(), and SINUCA3_DEBUG_PRINTF.
FinishSetup()
int EngineDebugComponent::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 111 of file engine_debug_component.cpp.
References shallFailOnFinish, and SINUCA3_DEBUG_PRINTF.
PrintConfigValue()
void EngineDebugComponent::PrintConfigValue (const char * parameter, ConfigValue value, unsigned char indent = 0) private
If true, fails at the FinishSetup method to test the engine handling of failures.
Prints a config value along with the parameter name. This is recursive for arrays.
Parameters
parameter self-explanatory.
value self-explanatory.
indent The indentation level for printing, increased every recursion.
Definition at line 32 of file engine_debug_component.cpp.
References PrintConfigValue(), and SINUCA3_DEBUG_PRINTF.
PrintStatistics()
void EngineDebugComponent::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 168 of file engine_debug_component.cpp.
References SINUCA3_LOG_PRINTF.
SetConfigParameter()
int EngineDebugComponent::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 71 of file engine_debug_component.cpp.
References Component< MessageType >::Connect(), fetch, fetchConnectionID, otherConnectionID, PrintConfigValue(), shallFailOnFinish, and SINUCA3_DEBUG_PRINTF.
Member Data Documentation
fetch
Component<FetchPacket>* EngineDebugComponent::fetch private
Another component to test sending messages.
Definition at line 43 of file engine_debug_component.hpp.
fetchConnectionID
int EngineDebugComponent::fetchConnectionID private
Connection ID for other.
Definition at line 45 of file engine_debug_component.hpp.
other
EngineDebugComponent* EngineDebugComponent::other private
Definition at line 41 of file engine_debug_component.hpp.
otherConnectionID
int EngineDebugComponent::otherConnectionID private
Another component to test fetching instructions.
Definition at line 44 of file engine_debug_component.hpp.
send
bool EngineDebugComponent::send private
Connection ID for fetch.
Definition at line 46 of file engine_debug_component.hpp.
shallFailOnFinish
bool EngineDebugComponent::shallFailOnFinish private
Tells wether we already sent a message to other.
Definition at line 47 of file engine_debug_component.hpp.
The documentation for this class was generated from the following files:
src/std_components/engine_debug_component.hpp
src/std_components/engine_debug_component.cpp