SiNUCA3: HardwiredPredictor Class Reference
HardwiredPredictor Class Reference
The HardwiredPredictor is a predictor that always predicted correctly or misspredicts a given set of instructions. It accepts the following boolean parameters, each one if false makes the predictor always misspredicts the given instruction set: syscall, call, return, uncond, cond and noBranch. The default for every set is true. Additionally, it accepts a sendTo Component<PredictorPacket> parameter. If sendTo is set, the predictor sends all responses to that component instead of sending in the response channel.
#include <hardwired_predictor.hpp>
Public Member Functions
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< PredictorPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, PredictorPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, PredictorPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
int SetBoolParameter (const char *parameter, bool *ptr, ConfigValue value)
Wether to predict normal instructions correctly.
void Respond (int id, PredictorPacket request)
Helper to respond a request.
Private Attributes
Component< PredictorPacket > * sendTo
unsigned long numberOfSyscalls
If set, sends responses to this component.
unsigned long numberOfCalls
Number of syscalls executed.
unsigned long numberOfRets
Number of calls executed.
unsigned long numberOfUnconds
Number of returns executed.
unsigned long numberOfConds
Number of unconditional branchs executed.
unsigned long numberOfNoBranchs
Number of conditional branchs executed.
int sendToID
Number of normal instructions executed.
bool syscall
ID of sendTo.
bool call
Wether to predict syscalls correctly.
bool ret
Wether to predict calls correctly.
bool uncond
Wether to predict returns correctly.
bool cond
Wether to predict unconditional branches correctly.
bool noBranch
Wether to predict conditional branches correctly.
Additional Inherited Members
Protected Member Functions inherited from Component< PredictorPacket >
int SendResponseToConnection (int connectionID, PredictorPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, PredictorPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
The HardwiredPredictor is a predictor that always predicted correctly or misspredicts a given set of instructions. It accepts the following boolean parameters, each one if false makes the predictor always misspredicts the given instruction set: syscall, call, return, uncond, cond and noBranch. The default for every set is true. Additionally, it accepts a sendTo Component<PredictorPacket> parameter. If sendTo is set, the predictor sends all responses to that component instead of sending in the response channel.
Definition at line 39 of file hardwired_predictor.hpp.
Constructor & Destructor Documentation
HardwiredPredictor()
HardwiredPredictor::HardwiredPredictor () inline
Definition at line 80 of file hardwired_predictor.hpp.
~HardwiredPredictor()
HardwiredPredictor::~HardwiredPredictor () virtual
Definition at line 163 of file hardwired_predictor.cpp.
Member Function Documentation
Clock()
void HardwiredPredictor::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 132 of file hardwired_predictor.cpp.
References Linkable::GetNumberOfConnections(), Linkable::numberOfConnections, Component< PredictorPacket >::ReceiveRequestFromConnection(), and Respond().
FinishSetup()
int HardwiredPredictor::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 29 of file hardwired_predictor.cpp.
References Component< MessageType >::Connect(), and sendToID.
PrintStatistics()
void HardwiredPredictor::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 142 of file hardwired_predictor.cpp.
References call, cond, noBranch, numberOfCalls, numberOfConds, numberOfNoBranchs, numberOfRets, numberOfSyscalls, numberOfUnconds, ret, SINUCA3_LOG_PRINTF, syscall, and uncond.
Respond()
void HardwiredPredictor::Respond (int id, PredictorPacket request) private
Helper to respond a request.
Parameters
id The connection id of the client.
request The request itself.
Definition at line 82 of file hardwired_predictor.cpp.
References call, cond, noBranch, numberOfCalls, numberOfConds, numberOfNoBranchs, numberOfRets, numberOfSyscalls, numberOfUnconds, PredictorPacket::response, ret, Component< MessageType >::SendRequest(), Component< PredictorPacket >::SendResponseToConnection(), sendToID, syscall, PredictorPacket::target, PredictorPacket::type, and uncond.
SetBoolParameter()
int HardwiredPredictor::SetBoolParameter (const char * parameter, bool * ptr, ConfigValue value) private
Wether to predict normal instructions correctly.
Helper to set all those boolean parameters.
Parameters
parameter The name of the parameter to set (for printing the error message if necessary).
ptr The pointer to the boolean parameter (&this->syscall, &this->call, etc).
value The value.
Definition at line 37 of file hardwired_predictor.cpp.
References SINUCA3_ERROR_PRINTF.
SetConfigParameter()
int HardwiredPredictor::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 50 of file hardwired_predictor.cpp.
References call, cond, noBranch, ret, SetBoolParameter(), SINUCA3_ERROR_PRINTF, syscall, and uncond.
Member Data Documentation
call
bool HardwiredPredictor::call private
Wether to predict syscalls correctly.
Definition at line 54 of file hardwired_predictor.hpp.
cond
bool HardwiredPredictor::cond private
Wether to predict unconditional branches correctly.
Definition at line 58 of file hardwired_predictor.hpp.
noBranch
bool HardwiredPredictor::noBranch private
Wether to predict conditional branches correctly.
Definition at line 60 of file hardwired_predictor.hpp.
numberOfCalls
unsigned long HardwiredPredictor::numberOfCalls private
Number of syscalls executed.
Definition at line 44 of file hardwired_predictor.hpp.
numberOfConds
unsigned long HardwiredPredictor::numberOfConds private
Number of unconditional branchs executed.
Definition at line 49 of file hardwired_predictor.hpp.
numberOfNoBranchs
unsigned long HardwiredPredictor::numberOfNoBranchs private
Number of conditional branchs executed.
Definition at line 51 of file hardwired_predictor.hpp.
numberOfRets
unsigned long HardwiredPredictor::numberOfRets private
Number of calls executed.
Definition at line 45 of file hardwired_predictor.hpp.
numberOfSyscalls
unsigned long HardwiredPredictor::numberOfSyscalls private
If set, sends responses to this component.
Definition at line 43 of file hardwired_predictor.hpp.
numberOfUnconds
unsigned long HardwiredPredictor::numberOfUnconds private
Number of returns executed.
Definition at line 47 of file hardwired_predictor.hpp.
ret
bool HardwiredPredictor::ret private
Wether to predict calls correctly.
Definition at line 55 of file hardwired_predictor.hpp.
sendTo
Component<PredictorPacket>* HardwiredPredictor::sendTo private
Definition at line 42 of file hardwired_predictor.hpp.
sendToID
int HardwiredPredictor::sendToID private
Number of normal instructions executed.
Definition at line 52 of file hardwired_predictor.hpp.
syscall
bool HardwiredPredictor::syscall private
ID of sendTo.
Definition at line 53 of file hardwired_predictor.hpp.
uncond
bool HardwiredPredictor::uncond private
Wether to predict returns correctly.
Definition at line 56 of file hardwired_predictor.hpp.
The documentation for this class was generated from the following files:
src/std_components/predictors/hardwired_predictor.hpp
src/std_components/predictors/hardwired_predictor.cpp