SiNUCA3: SimpleInstructionMemory Class Reference
SimpleInstructionMemory Class Reference
component for SiNUCA3 which just responds immediatly for every request (of instructions). I.e., the perfect (instruction) memory: big and works at the light speed!
#include <simple_instruction_memory.hpp>
Public Member Functions
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< InstructionPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, InstructionPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, InstructionPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Attributes
Component< InstructionPacket > * sendTo
unsigned long numberOfRequests
int sendToID
Additional Inherited Members
Protected Member Functions inherited from Component< InstructionPacket >
int SendResponseToConnection (int connectionID, InstructionPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, InstructionPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
component for SiNUCA3 which just responds immediatly for every request (of instructions). I.e., the perfect (instruction) memory: big and works at the light speed!
The SimpleInstructionMemory accepts the sendTo parameter as a Component<InstructionPacket>. If it's set, the memory forwards all responses to it instead of answering in the response channel. Beware that it connects to sendTo without limits, so if that component has a limited throughput, the buffer may start to eat all the system's memory and instructions will be waiting idling.
Definition at line 41 of file simple_instruction_memory.hpp.
Constructor & Destructor Documentation
SimpleInstructionMemory()
SimpleInstructionMemory::SimpleInstructionMemory () inline
Definition at line 48 of file simple_instruction_memory.hpp.
~SimpleInstructionMemory()
SimpleInstructionMemory::~SimpleInstructionMemory ()
Definition at line 74 of file simple_instruction_memory.cpp.
Member Function Documentation
Clock()
void SimpleInstructionMemory::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 54 of file simple_instruction_memory.cpp.
References Linkable::GetNumberOfConnections(), Linkable::numberOfConnections, Component< InstructionPacket >::ReceiveRequestFromConnection(), Component< MessageType >::SendRequest(), and Component< InstructionPacket >::SendResponseToConnection().
FinishSetup()
int SimpleInstructionMemory::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 47 of file simple_instruction_memory.cpp.
References Component< MessageType >::Connect().
PrintStatistics()
void SimpleInstructionMemory::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 69 of file simple_instruction_memory.cpp.
References SINUCA3_LOG_PRINTF.
SetConfigParameter()
int SimpleInstructionMemory::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 27 of file simple_instruction_memory.cpp.
References SINUCA3_ERROR_PRINTF.
Member Data Documentation
numberOfRequests
unsigned long SimpleInstructionMemory::numberOfRequests private
Definition at line 44 of file simple_instruction_memory.hpp.
sendTo
Component<InstructionPacket>* SimpleInstructionMemory::sendTo private
Definition at line 43 of file simple_instruction_memory.hpp.
sendToID
int SimpleInstructionMemory::sendToID private
Definition at line 45 of file simple_instruction_memory.hpp.
The documentation for this class was generated from the following files:
src/std_components/memory/simple_instruction_memory.hpp
src/std_components/memory/simple_instruction_memory.cpp