SiNUCA3: SimpleMemory Class Reference
SimpleMemory Class Reference
#include <simple_memory.hpp>
Public Member Functions
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< MemoryPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, MemoryPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, MemoryPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Attributes
unsigned long numberOfRequests
Additional Inherited Members
Protected Member Functions inherited from Component< MemoryPacket >
int SendResponseToConnection (int connectionID, MemoryPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, MemoryPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
SimpleMemory is a MemoryComponent that just responds immediatly for every request. I.e., it's the perfect memory: big and works at the light speed!
Definition at line 35 of file simple_memory.hpp.
Constructor & Destructor Documentation
SimpleMemory()
SimpleMemory::SimpleMemory () inline
Definition at line 40 of file simple_memory.hpp.
~SimpleMemory()
SimpleMemory::~SimpleMemory ()
Definition at line 52 of file simple_memory.cpp.
Member Function Documentation
Clock()
void SimpleMemory::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 36 of file simple_memory.cpp.
References Linkable::GetNumberOfConnections(), Linkable::numberOfConnections, Component< MemoryPacket >::ReceiveRequestFromConnection(), and Component< MemoryPacket >::SendResponseToConnection().
FinishSetup()
int SimpleMemory::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 34 of file simple_memory.cpp.
PrintStatistics()
void SimpleMemory::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 47 of file simple_memory.cpp.
References SINUCA3_LOG_PRINTF.
SetConfigParameter()
int SimpleMemory::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 27 of file simple_memory.cpp.
Member Data Documentation
numberOfRequests
unsigned long SimpleMemory::numberOfRequests private
Definition at line 37 of file simple_memory.hpp.
The documentation for this class was generated from the following files:
src/std_components/memory/simple_memory.hpp
src/std_components/memory/simple_memory.cpp