SiNUCA3: Fetcher Class Reference
Fetcher Class Reference
The Fetcher is a generic fetcher with support to an instruction memory and a predictor. It handles the pay of misspredicton penalties.
#include <fetcher.hpp>
Public Member Functions
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< int >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, int *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, int *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
int FetchConfigParameter (ConfigValue value)
Flags to check when removing instructions from the buffer. If there's a predictor, we need to check wether the instruction was predicted. If there's no predictor, we don't.
int InstructionMemoryConfigParameter (ConfigValue value)
Helper to set the instruction memory config parameter.
int FetchSizeConfigParameter (ConfigValue value)
Helper to set the fetch size config parameter.
int FetchIntervalConfigParameter (ConfigValue value)
Helper to set the fetch interval config parameter.
int PredictorConfigParameter (ConfigValue value)
Helper to set the predictor config parameter.
int MisspredictPenaltyConfigParameter (ConfigValue value)
Helper to set the missprediction penalty config parameter.
void ClockSendBuffered ()
Helper to send the fetched instructions to the memory and the predictor.
int ClockCheckPredictor ()
Helper to check predicted instructions.
void ClockUnbuffer ()
Helper to remove instructions from the buffer.
void ClockRequestFetch ()
Helper to request instructions to fetch.
void ClockFetch ()
Helper to get the fetched instructions.
Private Attributes
Component< FetchPacket > * fetch
Component< InstructionPacket > * instructionMemory
Component from which to fetch instructions.
Component< PredictorPacket > * predictor
Component to which send the instructions after fetching.
FetchBufferEntry * fetchBuffer
Component to which send prediction requests.
unsigned long fetchBufferUsage
Fetched instructions.
unsigned long fetchSize
Number of instructions in fetchBuffer.
unsigned long fetchInterval
Amount of bytes to fetch.
unsigned long fetchClock
Cycle interval to fetch.
unsigned long misspredictPenalty
Counter to control when to fetch.
unsigned long misspredictions
Amount of cycles to idle when a missprediction happens.
unsigned long currentPenalty
Number of misspredictions that happened.
unsigned long fetchedInstructions
Counter to control the paying of penalties.
int predictorID
Number of fetched instructions.
int fetchID
Connection ID of predictor.
int instructionMemoryID
Connection ID of fetch.
FetchBufferEntryFlags flagsToCheck
Connection ID of instructionMemory.
Additional Inherited Members
Protected Member Functions inherited from Component< int >
int SendResponseToConnection (int connectionID, int *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, int *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
The Fetcher is a generic fetcher with support to an instruction memory and a predictor. It handles the pay of misspredicton penalties.
It accepts the following parameters:
fetch (required): Component<InstructionPacket> from which to fetch instructions.
instructionMemory (required): Component<InstructionPacket> to which send the instruction after fetching.
fetchSize: The size in bytes to fetch per fetch cycle. Defaults to 0.
fetchInterval: Integer amount of cycles to wait before fetching. I.e., fetch every fetchInterval cycles. Defaults to 1.
predictor: Component<InstructionPacket> to which send prediction requests.
misspredictPenalty: Integer amount of cycles to idle when a missprediction happens.
Definition at line 70 of file fetcher.hpp.
Constructor & Destructor Documentation
Fetcher()
Fetcher::Fetcher () inline
Definition at line 128 of file fetcher.hpp.
~Fetcher()
Fetcher::~Fetcher () virtual
Definition at line 295 of file fetcher.cpp.
Member Function Documentation
Clock()
void Fetcher::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 258 of file fetcher.cpp.
References ClockCheckPredictor(), ClockFetch(), ClockRequestFetch(), ClockSendBuffered(), ClockUnbuffer(), currentPenalty, fetchClock, fetchInterval, misspredictions, and misspredictPenalty.
ClockCheckPredictor()
int Fetcher::ClockCheckPredictor () private
Helper to check predicted instructions.
Definition at line 189 of file fetcher.cpp.
References fetchBuffer, FetchBufferEntryFlagsPredicted, predictor, Component< MessageType >::ReceiveResponse(), PredictorPacket::response, PredictorPacket::target, and PredictorPacket::type.
ClockFetch()
void Fetcher::ClockFetch () private
Helper to get the fetched instructions.
Definition at line 245 of file fetcher.cpp.
References fetchBuffer, fetchBufferUsage, fetchedInstructions, and Component< MessageType >::ReceiveResponse().
ClockRequestFetch()
void Fetcher::ClockRequestFetch () private
Helper to request instructions to fetch.
Definition at line 233 of file fetcher.cpp.
References fetchBuffer, fetchBufferUsage, fetchID, fetchSize, and Component< MessageType >::SendRequest().
ClockSendBuffered()
void Fetcher::ClockSendBuffered () private
Helper to send the fetched instructions to the memory and the predictor.
Definition at line 155 of file fetcher.cpp.
References fetchBuffer, FetchBufferEntryFlagsSentToMemory, FetchBufferEntryFlagsSentToPredictor, fetchBufferUsage, instructionMemory, predictor, Component< MessageType >::SendRequest(), and PredictorPacket::type.
ClockUnbuffer()
void Fetcher::ClockUnbuffer () private
Helper to remove instructions from the buffer.
Definition at line 219 of file fetcher.cpp.
References fetchBuffer, fetchBufferUsage, and flagsToCheck.
FetchConfigParameter()
int Fetcher::FetchConfigParameter (ConfigValue value) private
Flags to check when removing instructions from the buffer. If there's a predictor, we need to check wether the instruction was predicted. If there's no predictor, we don't.
Helper to set the fetch config parameter.
Definition at line 57 of file fetcher.cpp.
References SINUCA3_ERROR_PRINTF.
FetchIntervalConfigParameter()
int Fetcher::FetchIntervalConfigParameter (ConfigValue value) private
Helper to set the fetch interval config parameter.
Definition at line 98 of file fetcher.cpp.
References fetchInterval, and SINUCA3_ERROR_PRINTF.
FetchSizeConfigParameter()
int Fetcher::FetchSizeConfigParameter (ConfigValue value) private
Helper to set the fetch size config parameter.
Definition at line 85 of file fetcher.cpp.
References fetchSize, and SINUCA3_ERROR_PRINTF.
FinishSetup()
int Fetcher::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 29 of file fetcher.cpp.
References Component< MessageType >::Connect(), fetchBuffer, FetchBufferEntryFlagsPredicted, fetchID, fetchSize, flagsToCheck, instructionMemory, instructionMemoryID, predictor, predictorID, and SINUCA3_ERROR_PRINTF.
InstructionMemoryConfigParameter()
int Fetcher::InstructionMemoryConfigParameter (ConfigValue value) private
Helper to set the instruction memory config parameter.
Definition at line 70 of file fetcher.cpp.
References instructionMemory, and SINUCA3_ERROR_PRINTF.
MisspredictPenaltyConfigParameter()
int Fetcher::MisspredictPenaltyConfigParameter (ConfigValue value) private
Helper to set the missprediction penalty config parameter.
Definition at line 123 of file fetcher.cpp.
References misspredictPenalty, and SINUCA3_ERROR_PRINTF.
PredictorConfigParameter()
int Fetcher::PredictorConfigParameter (ConfigValue value) private
Helper to set the predictor config parameter.
Definition at line 110 of file fetcher.cpp.
References predictor, and SINUCA3_ERROR_PRINTF.
PrintStatistics()
void Fetcher::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 288 of file fetcher.cpp.
References fetchedInstructions, misspredictions, and SINUCA3_LOG_PRINTF.
SetConfigParameter()
int Fetcher::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 135 of file fetcher.cpp.
References FetchConfigParameter(), FetchIntervalConfigParameter(), FetchSizeConfigParameter(), InstructionMemoryConfigParameter(), MisspredictPenaltyConfigParameter(), PredictorConfigParameter(), and SINUCA3_ERROR_PRINTF.
Member Data Documentation
currentPenalty
unsigned long Fetcher::currentPenalty private
Number of misspredictions that happened.
Definition at line 89 of file fetcher.hpp.
fetch
Component<FetchPacket>* Fetcher::fetch private
Definition at line 73 of file fetcher.hpp.
fetchBuffer
FetchBufferEntry* Fetcher::fetchBuffer private
Component to which send prediction requests.
Definition at line 79 of file fetcher.hpp.
fetchBufferUsage
unsigned long Fetcher::fetchBufferUsage private
Fetched instructions.
Definition at line 81 of file fetcher.hpp.
fetchClock
unsigned long Fetcher::fetchClock private
Cycle interval to fetch.
Definition at line 84 of file fetcher.hpp.
fetchedInstructions
unsigned long Fetcher::fetchedInstructions private
Counter to control the paying of penalties.
Definition at line 92 of file fetcher.hpp.
fetchID
int Fetcher::fetchID private
Connection ID of predictor.
Definition at line 94 of file fetcher.hpp.
fetchInterval
unsigned long Fetcher::fetchInterval private
Amount of bytes to fetch.
Definition at line 83 of file fetcher.hpp.
fetchSize
unsigned long Fetcher::fetchSize private
Number of instructions in fetchBuffer.
Definition at line 82 of file fetcher.hpp.
flagsToCheck
FetchBufferEntryFlags Fetcher::flagsToCheck private
Connection ID of instructionMemory.
Definition at line 97 of file fetcher.hpp.
instructionMemory
Component<InstructionPacket>* Fetcher::instructionMemory private
Component from which to fetch instructions.
Definition at line 75 of file fetcher.hpp.
instructionMemoryID
int Fetcher::instructionMemoryID private
Connection ID of fetch.
Definition at line 95 of file fetcher.hpp.
misspredictions
unsigned long Fetcher::misspredictions private
Amount of cycles to idle when a missprediction happens.
Definition at line 88 of file fetcher.hpp.
misspredictPenalty
unsigned long Fetcher::misspredictPenalty private
Counter to control when to fetch.
Definition at line 85 of file fetcher.hpp.
predictor
Component<PredictorPacket>* Fetcher::predictor private
Component to which send the instructions after fetching.
Definition at line 78 of file fetcher.hpp.
predictorID
int Fetcher::predictorID private
Number of fetched instructions.
Definition at line 93 of file fetcher.hpp.
The documentation for this class was generated from the following files:
src/std_components/fetch/fetcher.hpp
src/std_components/fetch/fetcher.cpp