SiNUCA3: Component< MessageType > Class Template Reference
Component< MessageType > Class Template Reference
#include <component.hpp>
Public Member Functions
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, MessageType *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, MessageType *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
virtual int FinishSetup ()=0
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)=0
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()=0
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()=0
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Protected Member Functions
int SendResponseToConnection (int connectionID, MessageType *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, MessageType *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
template<typename MessageType>
class Component< MessageType >
All components shall inherit from this class. The MessageType type parameter defines the message type the component receives from other components. If the component does not receive any message, int can be used as a placeholder. Note that Component<T> is just a wrapper for the underlying mother class Linkable. This is done to centralize the message-passing implementation in a non-template class for optimization reasons. This wrapper allows a nice and type-safe API on top of a single, fast and generic implementation.
Avoiding big types in MessageType is a good idea, because they're passed by value.
Definition at line 42 of file component.hpp.
Constructor & Destructor Documentation
Component()
template<typename MessageType > Component< MessageType >::Component () inline
Parameters
messageSize The size of the message that will be used by the component.
Definition at line 70 of file component.hpp.
~Component()
template<typename MessageType > Component< MessageType >::~Component () inline
Definition at line 102 of file component.hpp.
Member Function Documentation
Connect()
template<typename MessageType > int Component< MessageType >::Connect (int bufferSize) inline
Connects to another component.
Parameters
component The component to connect to.
bufferSize The size of the buffer to be used.
Returns
The connection ID.
Definition at line 78 of file component.hpp.
References Linkable::ConnectUnsafe().
ReceiveRequestFromConnection()
template<typename MessageType > int Component< MessageType >::ReceiveRequestFromConnection (int connectionID, MessageType * message) inline protected
Receives a request from another component.
Parameters
connectionID The connection ID.
message The message to receive.
Returns
0 if successful, 1 otherwise.
Definition at line 61 of file component.hpp.
References Linkable::GetRequestUnsafe().
ReceiveResponse()
template<typename MessageType > int Component< MessageType >::ReceiveResponse (int connectionID, MessageType * message) inline
Receives a response from another component.
Parameters
component The component to receive the response from.
connectionID The connection ID.
message The message to receive.
Returns
0 if successful, 1 otherwise.
Definition at line 98 of file component.hpp.
References Linkable::GetResponseUnsafe().
SendRequest()
template<typename MessageType > int Component< MessageType >::SendRequest (int connectionID, MessageType * message) inline
Sends a request to another component.
Parameters
component The component to send the request to.
connectionID The connection ID.
message The message to send.
Returns
0 if successful, 1 otherwise.
Definition at line 87 of file component.hpp.
References Linkable::SendRequestUnsafe().
SendResponseToConnection()
template<typename MessageType > int Component< MessageType >::SendResponseToConnection (int connectionID, MessageType * message) inline protected
Sends a response to another component.
Parameters
component The component to send the response to.
connectionID The connection ID.
message The message to send.
Returns
0 if successful, 1 otherwise.
Definition at line 51 of file component.hpp.
References Linkable::SendResponseUnsafe().
The documentation for this class was generated from the following file:
src/engine/component.hpp