SiNUCA3: sinucaTracer::SinucaTraceReader Class Reference
sinucaTracer::SinucaTraceReader Class Reference
Public Member Functions
virtual int OpenTrace (const char *imageName, const char *sourceDir)
Class attributes initializer.
virtual void PrintStatistics ()
Any statistic of interest.
virtual int GetTotalThreads ()
virtual unsigned long GetTotalBBLs ()
Number of basic blocks in static trace.
virtual unsigned long GetTotalInstToBeFetched (int tid)
Number of instructions to be fetched.
virtual unsigned long GetNumberOfFetchedInst (int tid)
Number of currently fetched instructions.
virtual FetchResult Fetch (InstructionPacket *ret, int tid)
Get next executed instruction.
virtual void CloseTrace ()
Free allocated memory in OpenTrace.
Private Member Functions
int GenerateBinaryDict (StaticTraceFile *stFile)
Fill instructions dictionary.
Private Attributes
ThrInfo * thrsInfo
int totalThreads
unsigned int binaryTotalBBLs
unsigned int * binaryBBLsSize
InstructionInfo ** binaryDict
InstructionInfo * pool
Detailed Description
Definition at line 47 of file trace_reader.hpp.
Constructor & Destructor Documentation
~SinucaTraceReader()
sinucaTracer::SinucaTraceReader::~SinucaTraceReader () inline
Definition at line 80 of file trace_reader.hpp.
Member Function Documentation
CloseTrace()
void sinucaTracer::SinucaTraceReader::CloseTrace () virtual
Free allocated memory in OpenTrace.
Implements TraceReader.
Definition at line 51 of file trace_reader.cpp.
Fetch()
FetchResult sinucaTracer::SinucaTraceReader::Fetch (InstructionPacket * ret, int tid) virtual
Get next executed instruction.
Parameters
ret Pointer to struct that will be filled.
tid Thread identifier.
Implements TraceReader.
Definition at line 90 of file trace_reader.cpp.
References SINUCA3_DEBUG_PRINTF.
GenerateBinaryDict()
int sinucaTracer::SinucaTraceReader::GenerateBinaryDict (StaticTraceFile * stFile) private
Fill instructions dictionary.
Info per instruction: Address | Ins. Size | Base Reg | Index Reg | Is predicated | Is prefetch | Is indirect | Is !std mem op | Is read | Has read2 | Is write | Num. Write Regs | Num. Read Regs | Read Regs | Write Regs | Ins. Mnemonic | Branch Type
Returns
1 on failure, 0 otherwise.
Definition at line 58 of file trace_reader.cpp.
References sinucaTracer::StaticTraceFile::GetNewBBLSize(), sinucaTracer::StaticTraceFile::ReadNextInstruction(), and SINUCA3_DEBUG_PRINTF.
GetNumberOfFetchedInst()
unsigned long sinucaTracer::SinucaTraceReader::GetNumberOfFetchedInst (int tid) virtual
Number of currently fetched instructions.
Parameters
tid Thread Identifier.
Implements TraceReader.
Definition at line 131 of file trace_reader.cpp.
GetTotalBBLs()
unsigned long sinucaTracer::SinucaTraceReader::GetTotalBBLs () virtual
Number of basic blocks in static trace.
Implements TraceReader.
Definition at line 127 of file trace_reader.cpp.
GetTotalInstToBeFetched()
unsigned long sinucaTracer::SinucaTraceReader::GetTotalInstToBeFetched (int tid) virtual
Number of instructions to be fetched.
Parameters
tid Thread Identifier.
Implements TraceReader.
Definition at line 135 of file trace_reader.cpp.
GetTotalThreads()
int sinucaTracer::SinucaTraceReader::GetTotalThreads () virtual
Returns
Number of threads.
Implements TraceReader.
Definition at line 123 of file trace_reader.cpp.
OpenTrace()
int sinucaTracer::SinucaTraceReader::OpenTrace (const char * imageName, const char * sourceDir) virtual
Class attributes initializer.
Parameters
imageName Name of the executable used to generate the traces.
sourceDir Complete path to the directory that stores the traces.
Returns
Non-zero on failure.
Implements TraceReader.
Definition at line 28 of file trace_reader.cpp.
References binaryTotalBBLs, GenerateBinaryDict(), SINUCA3_ERROR_PRINTF, and thrsInfo.
PrintStatistics()
void sinucaTracer::SinucaTraceReader::PrintStatistics () virtual
Any statistic of interest.
Implements TraceReader.
Definition at line 140 of file trace_reader.cpp.
References SINUCA3_LOG_PRINTF.
Member Data Documentation
binaryBBLsSize
unsigned int* sinucaTracer::SinucaTraceReader::binaryBBLsSize private
Number of instructions per basic block.
Definition at line 54 of file trace_reader.hpp.
binaryDict
InstructionInfo** sinucaTracer::SinucaTraceReader::binaryDict private
Array containing all instructions.
Definition at line 55 of file trace_reader.hpp.
binaryTotalBBLs
unsigned int sinucaTracer::SinucaTraceReader::binaryTotalBBLs private
Number of basic blocks in static file.
Definition at line 53 of file trace_reader.hpp.
pool
InstructionInfo* sinucaTracer::SinucaTraceReader::pool private
Pool used for more efficient allocation.
Definition at line 56 of file trace_reader.hpp.
thrsInfo
ThrInfo* sinucaTracer::SinucaTraceReader::thrsInfo private
Information specific to each thread.
Definition at line 49 of file trace_reader.hpp.
totalThreads
int sinucaTracer::SinucaTraceReader::totalThreads private
Definition at line 51 of file trace_reader.hpp.
The documentation for this class was generated from the following files:
src/tracer/sinuca/trace_reader.hpp
src/tracer/sinuca/trace_reader.cpp