SiNUCA3: BranchTargetBuffer Class Reference
BranchTargetBuffer Class Reference
Public Member Functions
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< struct BTBPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, struct BTBPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, struct BTBPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
unsigned int CalculateBank (unsigned long address)
Calculate the bank based on address.
unsigned long CalculateTag (unsigned long address)
Calculate the tag based on address.
unsigned long CalculateIndex (unsigned long address)
Calculate the index based on address.
int RegisterNewBranch (const StaticInstructionInfo *instruction, unsigned long targetAddress)
Register a new branch in BTB.
int UpdateBranch (const StaticInstructionInfo *instruction, bool branchState)
Update a BTB entry.
void Query (const StaticInstructionInfo *instruction, int connectionID)
Method for Request Query.
int AddEntry (const StaticInstructionInfo *instruction, unsigned long targetAddress)
Method for RequestAddEntry.
int Update (const StaticInstructionInfo *instruction, bool branchState)
Method for RequestUpdate.
Private Attributes
BTBEntry ** btb
unsigned long numQueries
Component< BTBPacket > * sendTo
int sendToID
unsigned int interleavingFactor
unsigned int numEntries
unsigned int interleavingBits
unsigned int entriesBits
Additional Inherited Members
Protected Member Functions inherited from Component< struct BTBPacket >
int SendResponseToConnection (int connectionID, struct BTBPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, struct BTBPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
Definition at line 177 of file interleavedBTB.hpp.
Constructor & Destructor Documentation
BranchTargetBuffer()
BranchTargetBuffer::BranchTargetBuffer ()
Definition at line 95 of file interleavedBTB.cpp.
~BranchTargetBuffer()
BranchTargetBuffer::~BranchTargetBuffer ()
Definition at line 341 of file interleavedBTB.cpp.
Member Function Documentation
AddEntry()
int BranchTargetBuffer::AddEntry (const StaticInstructionInfo * instruction, unsigned long targetAddress) inline private
Method for RequestAddEntry.
Parameters
address The address of a branch instruction.
targetAddress The target address of the branch instruction.
A wrapper for the method of registering a new entry in the BTB.
Definition at line 294 of file interleavedBTB.cpp.
References RegisterNewBranch().
CalculateBank()
unsigned int BranchTargetBuffer::CalculateBank (unsigned long address) private
Calculate the bank based on address.
Parameters
address The address that will be used to calculate the bank.
Returns
Which bank the instruction is in.
Definition at line 196 of file interleavedBTB.cpp.
References interleavingBits.
CalculateIndex()
unsigned long BranchTargetBuffer::CalculateIndex (unsigned long address) private
Calculate the index based on address.
Parameters
address The address that will be used to calculate the index.
Returns
The index of branch, In which BTB entry is the branch located.
Definition at line 210 of file interleavedBTB.cpp.
References entriesBits, and interleavingBits.
CalculateTag()
unsigned long BranchTargetBuffer::CalculateTag (unsigned long address) private
Calculate the tag based on address.
Parameters
address The address that will be used to calculate the tag.
Returns
The tag of instruction block.
Definition at line 203 of file interleavedBTB.cpp.
References interleavingBits.
Clock()
void BranchTargetBuffer::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 304 of file interleavedBTB.cpp.
References AddEntry(), BTBPacket::branchState, Linkable::GetNumberOfConnections(), BTBPacket::instruction, Linkable::numberOfConnections, numQueries, Query(), Component< struct BTBPacket >::ReceiveRequestFromConnection(), BTBPacket::requestQuery, SINUCA3_WARNING_PRINTF, BTBPacket::target, and Update().
FinishSetup()
int BranchTargetBuffer::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 161 of file interleavedBTB.cpp.
References BTBEntry::Allocate(), btb, Component< MessageType >::Connect(), entriesBits, interleavingBits, interleavingFactor, numEntries, sendTo, sendToID, and SINUCA3_ERROR_PRINTF.
PrintStatistics()
void BranchTargetBuffer::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 336 of file interleavedBTB.cpp.
References numQueries, and SINUCA3_LOG_PRINTF.
Query()
void BranchTargetBuffer::Query (const StaticInstructionInfo * instruction, int connectionID) inline private
Method for Request Query.
Parameters
address The fetch address received by a request message.
connectionID The ID of the connection that received the request.
When it receives a request, the BTB checks that the address received is valid (if there is an entry in the BTB for it). Then, if it is valid, it checks the corresponding entry and sends a reply message containing the address of the next fetch block and a limited vector containing the prediction bits of the instructions in the current block. If it is invalid, it sends a reply message containing the address of the next sequential block (current address + interleaving factor) and a limited vector with all bits set to 1, assuming that all instructions in the block are predicted to execute.
Definition at line 236 of file interleavedBTB.cpp.
References btb, CalculateIndex(), CalculateTag(), BTBEntry::GetBranchType(), BTBEntry::GetPrediction(), BTBEntry::GetTag(), BTBEntry::GetTargetAddress(), BTBPacket::instruction, interleavingFactor, BTBPacket::numberOfBits, Component< MessageType >::SendRequest(), Component< struct BTBPacket >::SendResponseToConnection(), sendTo, sendToID, BTBPacket::target, and BTBPacket::validBits.
RegisterNewBranch()
int BranchTargetBuffer::RegisterNewBranch (const StaticInstructionInfo * instruction, unsigned long targetAddress) private
Register a new branch in BTB.
Parameters
address The branch address.
targetAddress The target of the branch.
type The type of branch.
Returns
0 if successfuly, 1 otherwise.
Definition at line 219 of file interleavedBTB.cpp.
References btb, CalculateBank(), CalculateIndex(), CalculateTag(), and BTBEntry::NewEntry().
SetConfigParameter()
int BranchTargetBuffer::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 103 of file interleavedBTB.cpp.
References interleavingFactor, numEntries, sendTo, SINUCA3_ERROR_PRINTF, and SINUCA3_WARNING_PRINTF.
Update()
int BranchTargetBuffer::Update (const StaticInstructionInfo * instruction, bool branchState) inline private
Method for RequestUpdate.
Parameters
address The address of a branch instruction.
branchState The Information on whether the branch has been taken.
A wrapper for the method of updating an entry in the BTB.
Definition at line 299 of file interleavedBTB.cpp.
References UpdateBranch().
UpdateBranch()
int BranchTargetBuffer::UpdateBranch (const StaticInstructionInfo * instruction, bool branchState) private
Update a BTB entry.
Parameters
address The branch address.
branchState The Information on whether the branch has been taken. or not.
Returns
0 if successfuly, 1 otherwise.
Definition at line 228 of file interleavedBTB.cpp.
References btb, CalculateBank(), CalculateIndex(), and BTBEntry::UpdateEntry().
Member Data Documentation
btb
BTBEntry** BranchTargetBuffer::btb private
The pointer to BTB struct.
Definition at line 179 of file interleavedBTB.hpp.
entriesBits
unsigned int BranchTargetBuffer::entriesBits private
Number of entries in bits.
Definition at line 192 of file interleavedBTB.hpp.
interleavingBits
unsigned int BranchTargetBuffer::interleavingBits private
InterleavingFactor in bits.
Definition at line 191 of file interleavedBTB.hpp.
interleavingFactor
unsigned int BranchTargetBuffer::interleavingFactor private
The interleaving factor, defining the number of banks in which the BTB is interleaved.
Definition at line 187 of file interleavedBTB.hpp.
numEntries
unsigned int BranchTargetBuffer::numEntries private
The number of BTB entries.
Definition at line 190 of file interleavedBTB.hpp.
numQueries
unsigned long BranchTargetBuffer::numQueries private
Number of queries executed.
Definition at line 180 of file interleavedBTB.hpp.
sendTo
Component<BTBPacket>* BranchTargetBuffer::sendTo private
Component to which forward responses.>
Definition at line 182 of file interleavedBTB.hpp.
sendToID
int BranchTargetBuffer::sendToID private
Connection ID of the forwardTo component.>
Definition at line 184 of file interleavedBTB.hpp.
The documentation for this class was generated from the following files:
src/std_components/predictors/interleavedBTB.hpp
src/std_components/predictors/interleavedBTB.cpp