SiNUCA3: EngineBuilder Class Reference
EngineBuilder Class Reference
Builds an Engine from a configuration file, with the single public method Instantiate.
#include <engine_builder.hpp>
Public Member Functions
Engine * Instantiate (const char *configFile)
Instantiates an Engine from a configuration file, returning NULL on error.
Private Member Functions
int AddComponentInstantiationFromYamlMapping (const char *name, const char *alias, const std::vector< yaml::YamlMappingEntry * > *config, builder::InstanceID *ret)
Simply adds an instantiation and a definition. Calls AddComponentDefinitionFromYamlMapping first, then creates an instance. Returns non-zero on error.
builder::DefinitionID AddComponentDefinitionFromYamlMapping (const char *name, const std::vector< yaml::YamlMappingEntry * > *config, builder::DefinitionID *ret)
Simply adds a definition, recursively. Returns non-zero on error.
builder::DefinitionID AddDummyDefinition (const char *name)
Adds a definition not yet defined.
builder::InstanceID AddDummyInstance (const char *alias)
Adds an instance not yet defined.
int YamlArray2Parameter (builder::Parameter *dest, const std::vector< yaml::YamlValue * > *array)
Makes an array of parameters from a YAML array.
int FillParametersAndClass (builder::DefinitionID id, const std::vector< yaml::YamlMappingEntry * > *config)
Fills the parameters and the class of a component. Parameter are translated with Yaml2Parameter.
builder::DefinitionID GetComponentDefinitionOrMakeDummy (const char *name)
If there's a component definition with the name passed, returns a pointer to it. Otherwise creates a dummy one and returns it's pointer.
builder::InstanceID GetComponentInstantiationOrMakeDummy (const char *alias)
If there's a component instance with the name passed, returns a pointer to it. Otherwise creates a dummy one and returns it's pointer.
int GetComponentDefinition (const char *name, builder::DefinitionID *ret)
Returns a definition with the name passed by reference. If it does not already exists, returns 1.
int GetComponentInstantiation (const char *alias, builder::InstanceID *ret)
Returns an instance with the name passed by reference. If it does not already exists, returns 1.
int Yaml2Parameter (const char *name, builder::Parameter *dest, const yaml::YamlValue *src)
Translates YAML to a parameter. This may recursively call AddComponentDefinitionFromYamlMapping.
int EnsureAllComponentsAreDefined ()
Returns 0 if all components have the alreadyDefined parameter set to true.
int TreatParameter (const char *name, const yaml::YamlValue *value)
Takes care of parameters in the configuration toplevel, i.e., calls the functions to create definitions, instances and deal with the cores parameter.
int SetupComponentConfig (const builder::InstanceID instance)
Pass the parameters to a component, with Parameter2ConfigValue. This method also resolves pointers to definitions, thus allocating more components.
int Parameter2ConfigValue (const builder::Parameter *parameter, ConfigValue *value)
Translates the intermediate representation of the parameter to the config API representation. Note that this function adds more instances when it encounters references to definitions.
int ArrayParameter2ConfigValue (const builder::ParameterArray *array, ConfigValue *value)
Called by Parameter2ConfigValue to translate array values.
Linkable * NewComponentFromDefinitionReference (builder::DefinitionID reference)
Called by Parameter2ConfigValue to create new instances from references to definitions.
int TreatInstantiateParameter (const yaml::YamlValue *value)
Creates an anonymous instance defined by the instantiate parameter.
Engine * FreeSelfOnInstantiationFailure (const yaml::YamlValue *yamlConfig)
Helper that frees all memory used by the builder and returns NULL (to be used as return this->FreeSelf...).
Engine * BuildEngine ()
After everything is done, constructs the engine.
Private Attributes
Engine * engine
What we're building.
std::vector< builder::ComponentDefinition > componentDefinitions
Part of the stuff we're going to produce.
std::vector< builder::ComponentInstantiation > components
Part of the stuff we're going to produce.
Detailed Description
Builds an Engine from a configuration file, with the single public method Instantiate.
Definition at line 245 of file engine_builder.hpp.
Constructor & Destructor Documentation
EngineBuilder()
EngineBuilder::EngineBuilder () inline
Definition at line 355 of file engine_builder.hpp.
Member Function Documentation
AddComponentDefinitionFromYamlMapping()
int EngineBuilder::AddComponentDefinitionFromYamlMapping (const char * name, const std::vector< yaml::YamlMappingEntry * > * config, builder::DefinitionID * ret) private
Simply adds a definition, recursively. Returns non-zero on error.
Definition at line 261 of file engine_builder.cpp.
References componentDefinitions, FillParametersAndClass(), GetComponentDefinition(), and SINUCA3_ERROR_PRINTF.
AddComponentInstantiationFromYamlMapping()
int EngineBuilder::AddComponentInstantiationFromYamlMapping (const char * name, const char * alias, const std::vector< yaml::YamlMappingEntry * > * config, builder::InstanceID * ret) private
Simply adds an instantiation and a definition. Calls AddComponentDefinitionFromYamlMapping first, then creates an instance. Returns non-zero on error.
Definition at line 288 of file engine_builder.cpp.
References AddComponentDefinitionFromYamlMapping(), builder::ComponentInstantiation::alreadyDefined, components, builder::ComponentInstantiation::definition, GetComponentInstantiation(), and SINUCA3_ERROR_PRINTF.
AddDummyDefinition()
builder::DefinitionID EngineBuilder::AddDummyDefinition (const char * name) private
Adds a definition not yet defined.
Definition at line 55 of file engine_builder.cpp.
References componentDefinitions.
AddDummyInstance()
builder::InstanceID EngineBuilder::AddDummyInstance (const char * alias) private
Adds an instance not yet defined.
Definition at line 62 of file engine_builder.cpp.
References components.
ArrayParameter2ConfigValue()
int EngineBuilder::ArrayParameter2ConfigValue (const builder::ParameterArray * array, ConfigValue * value) private
Called by Parameter2ConfigValue to translate array values.
Definition at line 430 of file engine_builder.cpp.
References Parameter2ConfigValue().
BuildEngine()
Engine * EngineBuilder::BuildEngine () private
After everything is done, constructs the engine.
Definition at line 580 of file engine_builder.cpp.
References components, engine, and Engine::Instantiate().
EnsureAllComponentsAreDefined()
int EngineBuilder::EnsureAllComponentsAreDefined () private
Returns 0 if all components have the alreadyDefined parameter set to true.
Definition at line 385 of file engine_builder.cpp.
References componentDefinitions, components, and SINUCA3_ERROR_PRINTF.
FillParametersAndClass()
int EngineBuilder::FillParametersAndClass (builder::DefinitionID id, const std::vector< yaml::YamlMappingEntry * > * config) private
Fills the parameters and the class of a component. Parameter are translated with Yaml2Parameter.
Definition at line 206 of file engine_builder.cpp.
References builder::ComponentDefinition::clazz, componentDefinitions, builder::ParameterMapItem::name, builder::ComponentDefinition::name, SINUCA3_DEBUG_PRINTF, SINUCA3_ERROR_PRINTF, builder::ParameterMap::size, and Yaml2Parameter().
FreeSelfOnInstantiationFailure()
Engine * EngineBuilder::FreeSelfOnInstantiationFailure (const yaml::YamlValue * yamlConfig) private
Helper that frees all memory used by the builder and returns NULL (to be used as return this->FreeSelf...).
Definition at line 413 of file engine_builder.cpp.
References components, and engine.
GetComponentDefinition()
int EngineBuilder::GetComponentDefinition (const char * name, builder::DefinitionID * ret) private
Returns a definition with the name passed by reference. If it does not already exists, returns 1.
Definition at line 69 of file engine_builder.cpp.
References componentDefinitions.
GetComponentDefinitionOrMakeDummy()
builder::DefinitionID EngineBuilder::GetComponentDefinitionOrMakeDummy (const char * name) private
If there's a component definition with the name passed, returns a pointer to it. Otherwise creates a dummy one and returns it's pointer.
Definition at line 99 of file engine_builder.cpp.
References AddDummyDefinition(), and GetComponentDefinition().
GetComponentInstantiation()
int EngineBuilder::GetComponentInstantiation (const char * alias, builder::InstanceID * ret) private
Returns an instance with the name passed by reference. If it does not already exists, returns 1.
Definition at line 84 of file engine_builder.cpp.
References components.
GetComponentInstantiationOrMakeDummy()
builder::InstanceID EngineBuilder::GetComponentInstantiationOrMakeDummy (const char * alias) private
If there's a component instance with the name passed, returns a pointer to it. Otherwise creates a dummy one and returns it's pointer.
Definition at line 108 of file engine_builder.cpp.
References AddDummyInstance(), and GetComponentInstantiation().
Instantiate()
Engine * EngineBuilder::Instantiate (const char * configFile)
Instantiates an Engine from a configuration file, returning NULL on error.
Definition at line 524 of file engine_builder.cpp.
References BuildEngine(), builder::ComponentDefinition::clazz, builder::ComponentInstantiation::component, componentDefinitions, components, builder::ComponentInstantiation::definition, engine, EnsureAllComponentsAreDefined(), Linkable::FinishSetup(), FreeSelfOnInstantiationFailure(), SetupComponentConfig(), SINUCA3_ERROR_PRINTF, TreatParameter(), and yaml::YamlValue::type.
NewComponentFromDefinitionReference()
Linkable * EngineBuilder::NewComponentFromDefinitionReference (builder::DefinitionID reference) private
Called by Parameter2ConfigValue to create new instances from references to definitions.
Definition at line 449 of file engine_builder.cpp.
References builder::ComponentInstantiation::component, componentDefinitions, components, and SINUCA3_ERROR_PRINTF.
Parameter2ConfigValue()
int EngineBuilder::Parameter2ConfigValue (const builder::Parameter * parameter, ConfigValue * value) private
Translates the intermediate representation of the parameter to the config API representation. Note that this function adds more instances when it encounters references to definitions.
Definition at line 470 of file engine_builder.cpp.
References ArrayParameter2ConfigValue(), components, NewComponentFromDefinitionReference(), and builder::Parameter::type.
SetupComponentConfig()
int EngineBuilder::SetupComponentConfig (const builder::InstanceID instance) private
Pass the parameters to a component, with Parameter2ConfigValue. This method also resolves pointers to definitions, thus allocating more components.
Definition at line 503 of file engine_builder.cpp.
References componentDefinitions, components, builder::ParameterMapItem::name, Parameter2ConfigValue(), and Linkable::SetConfigParameter().
TreatInstantiateParameter()
int EngineBuilder::TreatInstantiateParameter (const yaml::YamlValue * value) private
Creates an anonymous instance defined by the instantiate parameter.
Definition at line 321 of file engine_builder.cpp.
References AddComponentInstantiationFromYamlMapping(), GetComponentDefinitionOrMakeDummy(), NewComponentFromDefinitionReference(), SINUCA3_DEBUG_PRINTF, SINUCA3_ERROR_PRINTF, and yaml::YamlValue::type.
TreatParameter()
int EngineBuilder::TreatParameter (const char * name, const yaml::YamlValue * value) private
Takes care of parameters in the configuration toplevel, i.e., calls the functions to create definitions, instances and deal with the cores parameter.
Definition at line 347 of file engine_builder.cpp.
References AddComponentDefinitionFromYamlMapping(), AddComponentInstantiationFromYamlMapping(), yaml::YamlValue::anchor, SINUCA3_DEBUG_PRINTF, SINUCA3_ERROR_PRINTF, TreatInstantiateParameter(), and yaml::YamlValue::type.
Yaml2Parameter()
int EngineBuilder::Yaml2Parameter (const char * name, builder::Parameter * dest, const yaml::YamlValue * src) private
Translates YAML to a parameter. This may recursively call AddComponentDefinitionFromYamlMapping.
Definition at line 142 of file engine_builder.cpp.
References AddComponentDefinitionFromYamlMapping(), GetComponentDefinitionOrMakeDummy(), GetComponentInstantiationOrMakeDummy(), builder::Parameter::type, yaml::YamlValue::type, and YamlArray2Parameter().
YamlArray2Parameter()
int EngineBuilder::YamlArray2Parameter (builder::Parameter * dest, const std::vector< yaml::YamlValue * > * array) private
Makes an array of parameters from a YAML array.
Definition at line 129 of file engine_builder.cpp.
References Yaml2Parameter().
Member Data Documentation
componentDefinitions
std::vector<builder::ComponentDefinition> EngineBuilder::componentDefinitions private
Part of the stuff we're going to produce.
Vector of definitions that we fill throughout the reading of the configuration file.
Definition at line 257 of file engine_builder.hpp.
components
std::vector<builder::ComponentInstantiation> EngineBuilder::components private
Part of the stuff we're going to produce.
Vector of instances that we fill throughout the reading of the configuration file. The first element is guaranteed to be the engine itself.
Definition at line 264 of file engine_builder.hpp.
engine
Engine* EngineBuilder::engine private
What we're building.
Definition at line 250 of file engine_builder.hpp.
The documentation for this class was generated from the following files:
src/config/engine_builder.hpp
src/config/engine_builder.cpp