SiNUCA3: SimpleCore Class Reference
SimpleCore Class Reference
#include <simple_core.hpp>
Public Member Functions
SimpleCore ()
The connection ID of fetching.
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< InstructionPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, InstructionPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, InstructionPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Attributes
Component< MemoryPacket > * instructionMemory
Component< MemoryPacket > * dataMemory
The instruction memory.
Component< FetchPacket > * fetching
The data memory.
unsigned long numFetchedInstructions
The fetching.
int instructionConnectionID
The number of fetched instructions.
int dataConnectionID
The connection ID of instructionMemory.
int fetchingConnectionID
The connection ID of dataMemory.
Additional Inherited Members
Protected Member Functions inherited from Component< InstructionPacket >
int SendResponseToConnection (int connectionID, InstructionPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, InstructionPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
SimpleCore fetches an instruction from the required parameter fetching, a Component<InstructionPacket> and optionally queries two memories (without caring with the result at all) with the instruction. The two memories are passed as the Component<MemoryPacket> parameters instructionMemory and dataMemory.
Definition at line 36 of file simple_core.hpp.
Constructor & Destructor Documentation
SimpleCore()
SimpleCore::SimpleCore () inline
The connection ID of fetching.
Definition at line 51 of file simple_core.hpp.
~SimpleCore()
SimpleCore::~SimpleCore ()
Definition at line 134 of file simple_core.cpp.
Member Function Documentation
Clock()
void SimpleCore::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 97 of file simple_core.cpp.
References dataConnectionID, dataMemory, fetching, fetchingConnectionID, instructionConnectionID, numFetchedInstructions, Component< MessageType >::ReceiveResponse(), FetchPacket::response, and Component< MessageType >::SendRequest().
FinishSetup()
int SimpleCore::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 87 of file simple_core.cpp.
References fetching, and SINUCA3_ERROR_PRINTF.
PrintStatistics()
void SimpleCore::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 129 of file simple_core.cpp.
References numFetchedInstructions, and SINUCA3_LOG_PRINTF.
SetConfigParameter()
int SimpleCore::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 30 of file simple_core.cpp.
References Component< MessageType >::Connect(), dataConnectionID, dataMemory, fetching, fetchingConnectionID, instructionConnectionID, and SINUCA3_ERROR_PRINTF.
Member Data Documentation
dataConnectionID
int SimpleCore::dataConnectionID private
The connection ID of instructionMemory.
Definition at line 47 of file simple_core.hpp.
dataMemory
Component<MemoryPacket>* SimpleCore::dataMemory private
The instruction memory.
Definition at line 40 of file simple_core.hpp.
fetching
Component<FetchPacket>* SimpleCore::fetching private
The data memory.
Definition at line 41 of file simple_core.hpp.
fetchingConnectionID
int SimpleCore::fetchingConnectionID private
The connection ID of dataMemory.
Definition at line 48 of file simple_core.hpp.
instructionConnectionID
int SimpleCore::instructionConnectionID private
The number of fetched instructions.
Definition at line 45 of file simple_core.hpp.
instructionMemory
Component<MemoryPacket>* SimpleCore::instructionMemory private
Definition at line 39 of file simple_core.hpp.
numFetchedInstructions
unsigned long SimpleCore::numFetchedInstructions private
The fetching.
Definition at line 43 of file simple_core.hpp.
The documentation for this class was generated from the following files:
src/std_components/cores/simple_core.hpp
src/std_components/cores/simple_core.cpp