SiNUCA3: Ras Class Reference
Ras Class Reference
API of the Ras. A simple, generic return address stack. It does not care at all about wrong predictions.
#include <ras.hpp>
Public Member Functions
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< PredictorPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, PredictorPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, PredictorPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
void RequestQuery (InstructionPacket instruction, int connectionID)
void RequestUpdate (unsigned long targetAddress)
Private Attributes
Component< PredictorPacket > * sendTo
unsigned long * buffer
long size
long end
unsigned long numQueries
unsigned long numUpdates
int forwardToID
Additional Inherited Members
Protected Member Functions inherited from Component< PredictorPacket >
int SendResponseToConnection (int connectionID, PredictorPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, PredictorPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
API of the Ras. A simple, generic return address stack. It does not care at all about wrong predictions.
It does not checks wether the branch is a return on queries. Clients should make this check before sending a query request. It always responds with a ResponseTakeToAddress. It accepts the following parameters:
size (required): integer > 0, sets the ras buffer size.
sendTo: Component<PredictorPacket>, if exists, the Ras sends responses to this component instead of in the response channel.
Definition at line 40 of file ras.hpp.
Constructor & Destructor Documentation
Ras()
Ras::Ras () inline
Definition at line 56 of file ras.hpp.
~Ras()
Ras::~Ras () virtual
Definition at line 135 of file ras.cpp.
Member Function Documentation
Clock()
void Ras::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 107 of file ras.cpp.
References Linkable::GetNumberOfConnections(), Linkable::numberOfConnections, Component< PredictorPacket >::ReceiveRequestFromConnection(), PredictorPacket::requestUpdate, SINUCA3_WARNING_PRINTF, PredictorPacket::target, and PredictorPacket::type.
FinishSetup()
int Ras::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 27 of file ras.cpp.
References Component< MessageType >::Connect(), and SINUCA3_ERROR_PRINTF.
PrintStatistics()
void Ras::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 130 of file ras.cpp.
References SINUCA3_LOG_PRINTF.
RequestQuery()
void Ras::RequestQuery (InstructionPacket instruction, int connectionID) inline private
Definition at line 83 of file ras.cpp.
RequestUpdate()
void Ras::RequestUpdate (unsigned long targetAddress) inline private
Definition at line 100 of file ras.cpp.
SetConfigParameter()
int Ras::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 43 of file ras.cpp.
References SINUCA3_ERROR_PRINTF.
Member Data Documentation
buffer
unsigned long* Ras::buffer private
Definition at line 43 of file ras.hpp.
end
long Ras::end private
Definition at line 45 of file ras.hpp.
forwardToID
int Ras::forwardToID private
Definition at line 49 of file ras.hpp.
numQueries
unsigned long Ras::numQueries private
Definition at line 46 of file ras.hpp.
numUpdates
unsigned long Ras::numUpdates private
Definition at line 47 of file ras.hpp.
sendTo
Component<PredictorPacket>* Ras::sendTo private
Definition at line 42 of file ras.hpp.
size
long Ras::size private
Definition at line 44 of file ras.hpp.
The documentation for this class was generated from the following files:
src/std_components/predictors/ras.hpp
src/std_components/predictors/ras.cpp