SiNUCA3: Engine Class Reference
Engine Class Reference
The engine itself.
#include <engine.hpp>
Public Member Functions
void Instantiate (Linkable **components, long numberOfComponents)
Instantiates a simulation from the array of components.
int Simulate (TraceReader *traceReader)
Self-explanatory.
virtual int FinishSetup ()
This method should be declared here so the simulator can send the finish setup message.
virtual int SetConfigParameter (const char *parameter, ConfigValue value)
This method should be declared here so the simulator can send config parameters.
virtual void Clock ()
This method should be declared here so the simulator can send clock cycles.
virtual void PrintStatistics ()
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Public Member Functions inherited from Component< FetchPacket >
Component ()
int Connect (int bufferSize)
Connects to another component.
int SendRequest (int connectionID, FetchPacket *message)
Sends a request to another component.
int ReceiveResponse (int connectionID, FetchPacket *message)
Receives a response from another component.
Public Member Functions inherited from Linkable
Linkable (int messageSize)
long GetNumberOfConnections ()
Self-explanatory.
void PosClock ()
Don't call this method.
Private Member Functions
unsigned long GetTraceSize ()
Returns the number of instructions to be executed.
void PrintTime (time_t start, unsigned long cycle)
Prints the estimated remaining simulation time.
int SetupSimulation (TraceReader *traceReader)
Called at the beggining of Simulate().
int SendBufferedAndFetch (int id)
Auxiliar to Fetch().
void Fetch (int id, FetchPacket packet)
Responds to requests.
Private Attributes
Linkable ** components
TraceReader * traceReader
The components of the simulation INCLUDING THE ENGINE ITSELF, guaranteed to be the first element.
InstructionPacket * fetchBuffers
The trace reader.
long numberOfComponents
Fetch buffers for each connection.
long numberOfFetchers
The number of components.
unsigned long totalCycles
The number of components connected to the engine. I.e., cores.
unsigned long fetchedInstructions
Counter of cycles.
unsigned long traceSize
Counter of instructions fetched.
bool end
The total amount of instructions to be executed.
bool error
Will be set if the traceReader returns an error.
Additional Inherited Members
Protected Member Functions inherited from Component< FetchPacket >
int SendResponseToConnection (int connectionID, FetchPacket *message)
Sends a response to another component.
int ReceiveRequestFromConnection (int connectionID, FetchPacket *message)
Receives a request from another component.
Protected Member Functions inherited from Linkable
void AllocateConnectionsBuffer (long numberOfConnections)
Allocates the buffers with the specified number of connections.
void DeallocateConnectionsBuffer ()
Frees memory allocated for connections.
void AddConnection (Connection *newConnection)
Add the new connection in the connections array.
int ConnectUnsafe (int bufferSize)
Connect to this component.
int SendRequestUnsafe (int connectionID, void *messageInput)
Receive a request from other component. (The other calls this method)
int GetRequestUnsafe (int connectionID, void *messageOutput)
Gets a request message in the parameter.
int SendResponseUnsafe (int connectionID, void *messageInput)
Sends a reply to the connection.
int GetResponseUnsafe (int connectionID, void *messageOutput)
Gets a response message in the parameter. (The other calls this method)
Detailed Description
The engine itself.
A component may fetch an instruction by sending a message to the engine. In the configuration file, it's accessible via the pre-defined alias *ENGINE. Each connection to the engine represents a core.
Definition at line 36 of file engine.hpp.
Constructor & Destructor Documentation
Engine()
Engine::Engine () inline
Definition at line 80 of file engine.hpp.
~Engine()
Engine::~Engine () virtual
Definition at line 175 of file engine.cpp.
Member Function Documentation
Clock()
void Engine::Clock () virtual
This method should be declared here so the simulator can send clock cycles.
Implements Linkable.
Definition at line 80 of file engine.cpp.
References Fetch(), Linkable::GetNumberOfConnections(), Linkable::numberOfConnections, and Component< FetchPacket >::ReceiveRequestFromConnection().
Fetch()
void Engine::Fetch (int id, FetchPacket packet) private
Responds to requests.
Definition at line 64 of file engine.cpp.
References fetchBuffers, and SendBufferedAndFetch().
FinishSetup()
int Engine::FinishSetup () virtual
This method should be declared here so the simulator can send the finish setup message.
This method is called after the config file is and all parameters are set, so to finish any setup required by the component. Non-zero should be returned if any problem occurred (e.g., a required configuration parameter was not provided). The component is responsible for printing a proper error message describing what happened.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 29 of file engine.cpp.
GetTraceSize()
unsigned long Engine::GetTraceSize () private
Returns the number of instructions to be executed.
Definition at line 97 of file engine.cpp.
References TraceReader::GetTotalInstToBeFetched(), TraceReader::GetTotalThreads(), and traceReader.
Instantiate()
void Engine::Instantiate (Linkable ** components, long numberOfComponents) inline
Instantiates a simulation from the array of components.
Definition at line 91 of file engine.hpp.
References numberOfComponents.
PrintStatistics()
void Engine::PrintStatistics () virtual
This method is called by the engine after the simulation stops, so each component can print it's statistics.
Implements Linkable.
Definition at line 91 of file engine.cpp.
References fetchedInstructions, SINUCA3_LOG_PRINTF, and totalCycles.
PrintTime()
void Engine::PrintTime (time_t start, unsigned long cycle) private
Prints the estimated remaining simulation time.
Definition at line 105 of file engine.cpp.
References fetchedInstructions, SINUCA3_LOG_PRINTF, and traceSize.
SendBufferedAndFetch()
int Engine::SendBufferedAndFetch (int id) private
Auxiliar to Fetch().
Definition at line 37 of file engine.cpp.
References end, error, TraceReader::Fetch(), fetchBuffers, fetchedInstructions, Component< FetchPacket >::SendResponseToConnection(), SINUCA3_WARNING_PRINTF, and traceReader.
SetConfigParameter()
int Engine::SetConfigParameter (const char * parameter, ConfigValue value) virtual
This method should be declared here so the simulator can send config parameters.
This method is called if the config file defines a configuration parameter for the component. Again, non-zero should be returned on error and the component is responsible for printing a proper error message.
Parameters
parameter The name of the parameter provided.
value The value of the parameter provided.
Returns
Non-zero on error, 0 otherwise.
Implements Linkable.
Definition at line 31 of file engine.cpp.
SetupSimulation()
int Engine::SetupSimulation (TraceReader * traceReader) private
Called at the beggining of Simulate().
Definition at line 117 of file engine.cpp.
References TraceReader::Fetch(), fetchBuffers, fetchedInstructions, Linkable::GetNumberOfConnections(), numberOfFetchers, and traceReader.
Simulate()
int Engine::Simulate (TraceReader * traceReader)
Self-explanatory.
Returns
Non-zero if the simulation stopped because of a problem. 0 if it stopped normally.
Definition at line 134 of file engine.cpp.
References Clock(), end, error, GetTraceSize(), numberOfComponents, Linkable::PosClock(), Linkable::PrintStatistics(), PrintTime(), SetupSimulation(), SINUCA3_ERROR_PRINTF, SINUCA3_LOG_PRINTF, totalCycles, and traceSize.
Member Data Documentation
components
Linkable** Engine::components private
Definition at line 39 of file engine.hpp.
end
bool Engine::end private
The total amount of instructions to be executed.
Will be one when there's no more instructions in the trace file.
Definition at line 56 of file engine.hpp.
error
bool Engine::error private
Will be set if the traceReader returns an error.
Definition at line 58 of file engine.hpp.
fetchBuffers
InstructionPacket* Engine::fetchBuffers private
The trace reader.
Definition at line 43 of file engine.hpp.
fetchedInstructions
unsigned long Engine::fetchedInstructions private
Counter of cycles.
Definition at line 49 of file engine.hpp.
numberOfComponents
long Engine::numberOfComponents private
Fetch buffers for each connection.
Definition at line 44 of file engine.hpp.
numberOfFetchers
long Engine::numberOfFetchers private
The number of components.
Definition at line 45 of file engine.hpp.
totalCycles
unsigned long Engine::totalCycles private
The number of components connected to the engine. I.e., cores.
Definition at line 47 of file engine.hpp.
traceReader
TraceReader* Engine::traceReader private
The components of the simulation INCLUDING THE ENGINE ITSELF, guaranteed to be the first element.
Definition at line 41 of file engine.hpp.
traceSize
unsigned long Engine::traceSize private
Counter of instructions fetched.
Definition at line 50 of file engine.hpp.
The documentation for this class was generated from the following files:
src/engine/engine.hpp
src/engine/engine.cpp