SiNUCA3: src/std_components/misc/queue.hpp File Reference
queue.hpp File Reference
#include <sinuca3.hpp>
Classes
class Queue< Type >
Queue is a template class for creating fetching queues.
class QueueTester
Component for testing the Queue template class.
Functions
int TestQueue ()
Test for the Queue template class.
Detailed Description
API of the template Queue, a generic fetching queue that can be used to enqueue results from caches, predictors, etc. You need to create a proper component that instantiates this template class to use it.
Definition in file queue.hpp.
Function Documentation
TestQueue()
int TestQueue ()
Test for the Queue template class.
Definition at line 34 of file queue.cpp.
References Queue< Type >::Clock(), Component< MessageType >::Connect(), Queue< Type >::FinishSetup(), QueueTester::GetMessage(), Linkable::PosClock(), Component< MessageType >::SendRequest(), Queue< Type >::SetConfigParameter(), and SINUCA3_ERROR_PRINTF.