SiNUCA3: src/std_components/misc/queue.cpp File Reference
queue.cpp File Reference
#include "queue.hpp"
#include <config/config.hpp>
#include <sinuca3.hpp>
Functions
int TestQueue ()
Test for the Queue template class.
Detailed Description
Implementation of the template Queue, a generic fetching queue that can be used to enqueue results from caches, predictors, etc. You need to create a proper component that instantiates this template class to use it.
Definition in file queue.cpp.
Function Documentation
TestQueue()
int TestQueue ()
Test for the Queue template class.
Definition at line 34 of file queue.cpp.
References Queue< Type >::Clock(), Component< MessageType >::Connect(), Queue< Type >::FinishSetup(), QueueTester::GetMessage(), Linkable::PosClock(), Component< MessageType >::SendRequest(), Queue< Type >::SetConfigParameter(), and SINUCA3_ERROR_PRINTF.