SiNUCA3: Connection Struct Reference
Connection Struct Reference
Public Member Functions
void CreateBuffers (int bufferSize, int messageSize)
Allocate the buffers used to channels.
void DeleteBuffers ()
Free the memory allocated for the buffers.
int GetBufferSize () const
Self-explanatory.
int GetMessageSize () const
Self-explanatory.
void SwapBuffers ()
Swap the buffers of the connection.
bool InsertIntoRequestBuffer (int id, void *messageInput)
Insert a message into a requestBuffer.
bool InsertIntoResponseBuffer (int id, void *messageInput)
Send a message into a responseBuffer.
bool RemoveFromARequestBuffer (int id, void *messageOutput)
Remove a request from a requestBuffer.
bool RemoveFromAResponseBuffer (int id, void *messageOutput)
Remove a response from a responseBuffer.
Private Attributes
int bufferSize
int messageSize
CircularBuffer * requestBuffers [2]
CircularBuffer * responseBuffers [2]
Detailed Description
Definition at line 32 of file linkable.hpp.
Constructor & Destructor Documentation
Connection()
Connection::Connection () inline
Definition at line 42 of file linkable.hpp.
Member Function Documentation
CreateBuffers()
void Connection::CreateBuffers (int bufferSize, int messageSize)
Allocate the buffers used to channels.
Parameters
bufferSize self-explanatory.
messageSize self-explanatory.
Definition at line 25 of file linkable.cpp.
References CircularBuffer::Allocate(), requestBuffers, and responseBuffers.
DeleteBuffers()
void Connection::DeleteBuffers ()
Free the memory allocated for the buffers.
Definition at line 42 of file linkable.cpp.
References requestBuffers, and responseBuffers.
GetBufferSize()
int Connection::GetBufferSize () const inline
Self-explanatory.
Definition at line 49 of file linkable.cpp.
GetMessageSize()
int Connection::GetMessageSize () const inline
Self-explanatory.
Definition at line 51 of file linkable.cpp.
InsertIntoRequestBuffer()
bool Connection::InsertIntoRequestBuffer (int id, void * messageInput)
Insert a message into a requestBuffer.
Parameters
id The id of the buffer.
messageInput A pointer to the message to send.
Returns
0 if successfuly, 1 otherwise.
Definition at line 65 of file linkable.cpp.
References CircularBuffer::Enqueue(), and requestBuffers.
InsertIntoResponseBuffer()
bool Connection::InsertIntoResponseBuffer (int id, void * messageInput)
Send a message into a responseBuffer.
Parameters
id The id of the buffer.
messageInput A pointer to the message to send.
Returns
0 if successfuly, 1 otherwise.
Definition at line 69 of file linkable.cpp.
References CircularBuffer::Enqueue(), and responseBuffers.
RemoveFromARequestBuffer()
bool Connection::RemoveFromARequestBuffer (int id, void * messageOutput)
Remove a request from a requestBuffer.
Parameters
id The id of the buffer.
messageOutput Address where to send the message.
Returns
0 if successfuly, 1 otherwise.
Definition at line 73 of file linkable.cpp.
References CircularBuffer::Dequeue(), and requestBuffers.
RemoveFromAResponseBuffer()
bool Connection::RemoveFromAResponseBuffer (int id, void * messageOutput)
Remove a response from a responseBuffer.
Parameters
id The id of the buffer.
messageOutput Address where to send the message.
Returns
0 if successfuly, 1 otherwise.
Definition at line 77 of file linkable.cpp.
References CircularBuffer::Dequeue(), and responseBuffers.
SwapBuffers()
void Connection::SwapBuffers ()
Swap the buffers of the connection.
Definition at line 53 of file linkable.cpp.
References requestBuffers, and responseBuffers.
Member Data Documentation
bufferSize
int Connection::bufferSize private
Definition at line 34 of file linkable.hpp.
messageSize
int Connection::messageSize private
Definition at line 35 of file linkable.hpp.
requestBuffers
CircularBuffer* Connection::requestBuffers[2] private
Array of the request buffers, swapped each cycle.
Definition at line 36 of file linkable.hpp.
responseBuffers
CircularBuffer* Connection::responseBuffers[2] private
Array of the response buffers, swapped each cycle.
Definition at line 38 of file linkable.hpp.
The documentation for this struct was generated from the following files:
src/engine/linkable.hpp
src/engine/linkable.cpp